//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G02Apis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SinhVien()
        {
            this.Diems = new HashSet<Diem>();
            this.HocPhis = new HashSet<HocPhi>();
            this.VanBans = new HashSet<VanBan>();
        }
    
        public int Id { get; set; }
        public string MaSinhVien { get; set; }
        public string Email { get; set; }
        public string SDT { get; set; }
        public string CMND { get; set; }
        public string DiaChi { get; set; }
        public string Ho { get; set; }
        public string Ten { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public Nullable<int> KhoaId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> NguoiTao { get; set; }
        public Nullable<int> NgayTao { get; set; }
        public int TrangThai { get; set; }
        public Nullable<int> LopId { get; set; }
        public int UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diem> Diems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HocPhi> HocPhis { get; set; }
        public virtual LopSinhVien LopSinhVien { get; set; }
        public virtual S_Users S_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VanBan> VanBans { get; set; }
    }
}
