//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G02Apis.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SoHoaEntities : DbContext
    {
        public SoHoaEntities()
            : base("name=SoHoaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessToken> AccessTokens { get; set; }
        public virtual DbSet<Diem> Diems { get; set; }
        public virtual DbSet<HocKy> HocKies { get; set; }
        public virtual DbSet<HocPhi> HocPhis { get; set; }
        public virtual DbSet<Khoa> Khoas { get; set; }
        public virtual DbSet<LoaiVB> LoaiVBs { get; set; }
        public virtual DbSet<LopSinhVien> LopSinhViens { get; set; }
        public virtual DbSet<MonHoc> MonHocs { get; set; }
        public virtual DbSet<S_Authority> S_Authority { get; set; }
        public virtual DbSet<S_NhanVien> S_NhanVien { get; set; }
        public virtual DbSet<S_Role> S_Role { get; set; }
        public virtual DbSet<S_Role_URL> S_Role_URL { get; set; }
        public virtual DbSet<S_Uers_Atuthority> S_Uers_Atuthority { get; set; }
        public virtual DbSet<S_User_Role> S_User_Role { get; set; }
        public virtual DbSet<S_Users> S_Users { get; set; }
        public virtual DbSet<SinhVien> SinhViens { get; set; }
        public virtual DbSet<VanBan> VanBans { get; set; }
    }
}
