//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G02Apis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public int TinTucId { get; set; }
        public string Ten { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> NguoiTao { get; set; }
        public string NoiDungMo { get; set; }
        public string NoiDungThan { get; set; }
        public string NoiDungKet { get; set; }
        public string TieuDeMo { get; set; }
        public string TieuDeThan { get; set; }
        public string TieuDeKet { get; set; }
        public string AnhMo { get; set; }
        public string AnhThan { get; set; }
        public string AnhKet { get; set; }
    }
}
