//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G02Apis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VanBan
    {
        public int Id { get; set; }
        public Nullable<int> SinhVienId { get; set; }
        public Nullable<int> MaSinhVien { get; set; }
        public Nullable<int> NamThu { get; set; }
        public Nullable<int> SDT { get; set; }
        public string KhoaHoc { get; set; }
        public string QueQuan { get; set; }
        public string CMND { get; set; }
        public string NoiDung { get; set; }
        public string LyDo { get; set; }
        public bool DaXacMinh { get; set; }
        public bool IsPending { get; set; }
        public bool IsApproved { get; set; }
        public bool IsSolved { get; set; }
        public Nullable<int> LoaiVBId { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> NguoiTao { get; set; }
    
        public virtual LoaiVB LoaiVB { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
